version: "3"
services:
  reverseproxy:
    build:
        context: ./udagram-reverseproxy
    image: yohansto13/udagram-reverseproxy
  backend-user:
    build:
      context: ./udagram-api-user
    image: yohansto13/udagram-api-user
  backend-feed:
    build:
      context: ./udagram-api-feed
    image: yohansto13/udagram-api-feed
  frontend:
    build:
        context: ./udagram-frontend
    image: yohansto13/udagram-frontend